sudo: false
os: linux
compiler: gcc
language: cpp
#before_install:
script:
  - ls
  - echo Full Travis-CI implementation coming soon... (work on uconn/cmu_dev branch first)
# whitelist (only cmu_dev for now, where the Travis-CI work is going on)
branches:
  only:
    - cmu_dev
notifications:
    email:
      recipients:
        - cornejo@jlab.org
